excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://velocet.github.io
title: Maschinensprache
email: velocet@users.noreply.github.com
author: Velocet
tagline: digitales grundrauschen
description: radikale gedanken über liberale technik
paginate: 5
